config/routes.rb
Rails.application.routes.draw do

  devise_for :consultants
  devise_for :workers
  devise_for :admins

  root 'pages#index'
  get '/admin-page', to: 'pages#admin'
  get '/worker-page', to: 'pages#worker'
  get '/consultant-page', to: 'pages#consultant'
  get '/admin-phone-list', to: 'pages#adminphones'
  get '/admin-worker-list', to: 'pages#adminworkers'
  get '/admin-consultant-list', to: 'pages#adminconsultants'

  devise_for :users
  resources :phones
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :phones
  has_many :workers
  has_many :consultants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/consultant.rb
class Consultant < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :admin
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :admin
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/worker.rb
class Worker < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :admin
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
before_action :authenticate_admin!, only: [:admin, :adminphones, :adminworkers, :adminconsultants]
before_action :authenticate_worker!, only: [:worker]
before_action :authenticate_consultant!, only: [:consultant]

  def index
    @phones = Phone.all
  end

  def admin
    sign_out :user
    sign_out :worker
    sign_out :consultant
  end

  def worker
    sign_out :admin
    sign_out :user
    sign_out :consultant
  end

  def consultant
    sign_out :admin
    sign_out :user
    sign_out :worker
  end

  def adminphones
    @phones = Phone.all
  end

  def adminworkers
    @workers = current_admin.workers.all
  end

  def adminconsultants
    @cons = current_admin.consultants.all
  end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
before_action :authenticate_admin!, except: [:show]
  def new
    @phone = Phone.new
  end

  def create
    @phone = current_admin.phones.build(phone_params)
    if @phone.save
      redirect_to admin_page_path
    end
  end

  def show
    @phone = Phone.find(params[:id])
  end

  def edit
    @phone = Phone.find(params[:id])
  end

  def update
    @phone = Phone.find(params[:id])
    @phone.update(phone_params)
    if @phone.save
      redirect_to phone_path(@phone.id)
    end
  end

  def destroy
    @phone = Phone.find(params[:id])
    @phone.destroy
    redirect_to admin_page_path
  end

  private
    def phone_params
      params.require(:phone).permit(:admin_id, :price, :brand, :model, :materials, :color, :os, :displaysize, :displaytype, :displayresolution, :soc, :frequency, :gpu, :rom, :ram, :sims, :maincam, :frontcam, :videoresolution, :focus, :moreaboutcam, :battery, :fastcharge, :wireless, :year, :interfaces, :dimensions, :mass, :more, :description)
    end
end

app/controllers/workers/confirmations_controller.rb
# frozen_string_literal: true

class Workers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/workers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Workers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/workers/passwords_controller.rb
# frozen_string_literal: true

class Workers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/workers/registrations_controller.rb
# frozen_string_literal: true

class Workers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/workers/sessions_controller.rb
# frozen_string_literal: true

class Workers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/workers/unlocks_controller.rb
# frozen_string_literal: true

class Workers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' && Admin.all.size < 1%>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smartphone Shop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div style="top: 0px; left: 0px; width: 100%;
    position: fixed;
    top: 0px;
    left: 0px;
    padding: 4px;
    background-color: white;
    border-bottom-left-radius: 16px;
    border-bottom-right-radius: 16px;
    vertical-align: middle;
    box-shadow: 4px 2px 7px 3px rgba(0, 0, 0, 0.44);">
      <% if admin_signed_in? %>
        <strong><%= current_admin.email %>(admin)</strong> <%= link_to "Profile", edit_admin_registration_path %> <%= link_to "Log out", destroy_admin_session_path, method: :delete %>
        <%= link_to "View phones", admin_phone_list_path %>
        <%= link_to "View consultants" %>
        <%= link_to "View workers", admin_worker_list_path %>
      <% end %>
      <% if user_signed_in? %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete %>
            <%= link_to "My Profile" %>
        <% else %>
        <% if !admin_signed_in? && !worker_signed_in? && !consultant_signed_in? %>
            <%= link_to "Log in", new_user_session_path %>
        <% end %>
      <% end %>

      <% if worker_signed_in? %>
            <strong><%= current_worker.email %>(worker)</strong>
            <%= link_to "Profile", edit_worker_registration_path %>
            <%= link_to "Log out", destroy_worker_session_path, method: :delete %>
      <% end %>

      <% if consultant_signed_in? %>
            <strong><%= current_consultant.email %>(consultant)</strong>
            <%= link_to "Profile", edit_consultant_registration_path %>
            <%= link_to "Log out", destroy_consultant_session_path, method: :delete %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/admin.html.erb
<h2 style="margin-top: 40px">Adminka</h2>


<p>
  some statistics about workers
</p>

app/views/pages/adminphones.html.erb
<h2 style="margin-top: 40px">Smartphones</h2>
<p><%= link_to "Add phone", new_phone_path %><br>
<% if @phones == [] %>
    <p>No phones</p>
<% else %>
    <% @phones.each do |phone| %>
       <p><b><%= phone.brand %></b> <%= phone.model %> | <i><%= phone.price %> UAN</i> <%= link_to "Show", phone_path(phone.id) %> <%= link_to "Edit", edit_phone_path(phone.id) %> <%= link_to "Delete", phone_path(phone.id), method: :delete %><br>
    <% end %>
<% end %>

app/views/pages/adminworkers.html.erb
<h2 style="margin-top: 40px">Workers</h2>
<p><%= link_to "Add worker", new_worker_registration_path %><br>
<% if @workers == [] %>
    <p>No workers</p>
<% else %>
    <% @workers.each do |w| %>
       <% w.email %>
    <% end %>
<% end %>

app/views/pages/consultant.html.erb
<h2>Consultant</h2>

app/views/pages/index.html.erb
<h1 style="margin-top: 40px">Pages#index</h1>
<% @phones.each do |phone| %>
  <%= link_to phone_path(phone.id) do %>
    <p><%= phone.brand %> <%= phone.model %><% end %>
  <%= phone.price %> uan</p>
<% end %>

app/views/pages/worker.html.erb
<h2>Worker</h2>

app/views/phones/edit.html.erb
<div style="margin-top: 40px"/>
<%= form_for @phone, url: phone_path do |f| %>
Brand:
<%= f.text_field :brand %><br>
Model:
<%= f.text_field :model %><br>
Price:
<%= f.number_field :price %><br>
Materials:
<%= f.text_field :materials %><br>
Color:
<%= f.text_field :color %><br>
OS:
<%= f.text_field :os %><br>
Display diagonal (inches):
<%= f.text_field :displaysize %><br>
Display type:
<%= f.text_field :displaytype %><br>
Display resolution:
<%= f.text_field :displayresolution %><br>
System on a Chip:
<%= f.text_field :soc %><br>
Frequency:
<%= f.text_field :frequency %><br>
GPU:
<%= f.text_field :gpu %><br>
ROM storage:
<%= f.number_field :rom %><br>
RAM storage:
<%= f.number_field :ram %><br>
Number of SIM cards:
<%= f.number_field :sims %><br>
Main camera:
<%= f.text_field :maincam %><br>
Front camera:
<%= f.text_field :frontcam %><br>
Video resolution:
<%= f.text_field :videoresolution %><br>
Camera focus type:
<%= f.text_field :focus %><br>
More about cam:
<%= f.text_area :moreaboutcam, size: "60x12" %><br>
Battery size (mAh):
<%= f.number_field :battery %><br>
Fast charge:
<%= f.text_field :fastcharge %><br>
Wireless interfaces:
<%= f.text_area :wireless, size: "60x12" %><br>
Wire interfaces:
<%= f.text_field :fastcharge %><br>
Year:
<%= f.number_field :year %><br>
Dimensions:
<%= f.text_field :dimensions %><br>
Mass:
<%= f.number_field :mass %><br>
More:
<%= f.text_area :more, size: "60x12" %><br>
Description:
<%= f.text_area :description, size: "60x12" %><br>
<%= f.submit "Submit" %>
<% end %>

app/views/phones/new.html.erb
<div style="margin-top: 40px"/>
<%= form_for @phone, url: {action: "create"} do |f| %>
Brand:
<%= f.text_field :brand %><br>
Model:
<%= f.text_field :model %><br>
Price:
<%= f.number_field :price %><br>
Materials:
<%= f.text_field :materials %><br>
Color:
<%= f.text_field :color %><br>
OS:
<%= f.text_field :os %><br>
Display diagonal (inches):
<%= f.text_field :displaysize %><br>
Display type:
<%= f.text_field :displaytype %><br>
Display resolution:
<%= f.text_field :displayresolution %><br>
System on a Chip:
<%= f.text_field :soc %><br>
Frequency:
<%= f.text_field :frequency %><br>
GPU:
<%= f.text_field :gpu %><br>
ROM storage:
<%= f.number_field :rom %><br>
RAM storage:
<%= f.number_field :ram %><br>
Number of SIM cards:
<%= f.number_field :sims %><br>
Main camera:
<%= f.text_field :maincam %><br>
Front camera:
<%= f.text_field :frontcam %><br>
Video resolution:
<%= f.text_field :videoresolution %><br>
Camera focus type:
<%= f.text_field :focus %><br>
More about cam:
<%= f.text_area :moreaboutcam, size: "60x12" %><br>
Battery size (mAh):
<%= f.number_field :battery %><br>
Fast charge:
<%= f.text_field :fastcharge %><br>
Wireless interfaces:
<%= f.text_area :wireless, size: "60x12" %><br>
Wire interfaces:
<%= f.text_field :fastcharge %><br>
Year:
<%= f.number_field :year %><br>
Dimensions:
<%= f.text_field :dimensions %><br>
Mass:
<%= f.number_field :mass %><br>
More:
<%= f.text_area :more, size: "60x12" %><br>
Description:
<%= f.text_area :description, size: "60x12" %><br>
<%= f.submit "Add" %>
<% end %>

app/views/phones/show.html.erb
<div style="margin-top: 40px"/>
<%= @phone.brand %> <%= @phone.model %>
<p><small>Description:</small></p>
<%= @phone.description %>